### ISSUE TITLE
Voicemail issue upon creation of Extension

### ISSUE THREAD

**Issue by SimplySynced** [PhantomVl/sccp_manager#10]
When creating an extension and enabling the voicemail, the voicemail box does create.  You are able to leave a voicemail.  However the phone will not show the message waiting icon on the screen.  Enabling debugging in the sccp.conf and unloading/reloading the module you can see the mailbox is not being set.  Checking the realtime database table sccpline you can see the column mailbox is set to NULL upon creation and even editing the extension.  The Voicemail enabled toggle is set to yes.

**Comment by PhantomVl** [comment]
I slightly altered the Database. I hope this issue is fixed.
