### ISSUE TITLE
Spelling Corrections

### ISSUE THREAD

**Issue by GMeola** [PhantomVl/sccp_manager#11]
I found two minor English spelling errors in the Advanced Server config module page.

https://github.com/PhantomVl/sccp_manager/blob/4a0c77066f89a526f097d09c1700fc3f048c8354/views/advserver.model.php#L210

No awalable => Not Available
Tow ExpModule => Two ExpModule

Have a great day,
~Gary

**Comment by PhantomVl** [comment]
Corrected. Thank you.
