### ISSUE TITLE
Timezone Codes

### ISSUE THREAD

**Issue by TheBaldOne** [PhantomVl/sccp_manager#12]
Under the SCCP Time Service config, when selecting the time zone as Pacific/Auckland the SEPxxx.cnf.xml file is being populated with Pacific/Auckland instead of the correct Cisco Time Zone code of 'New Zealand Standard/Daylight Time'

Suggestion:
Maybe this could just be a text box that people can type the required Time Zone information linked to a Database Table instead of a drop down box.
or
An Import Button to import a list of Time Zones to a Database Table that then can be selected from the Drop Down Box.

**Comment by PhantomVl** [comment]
I hope that I managed to fix this problem.

**Comment by TheBaldOne** [comment]
Hi.

Sorry i had not got back to you but have been away. The New Zealand code is still incorrect.
Please have a look at the follow website for all the correct Cisco Local Time Zone names.
http://usecallmanager.nz/sepmac-cnf-xml.html#networkLocale/name
