### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by kh0952** [PhantomVl/sccp_manager#15]
I'm getting the following error when trying to install using fwconsole.  Installation from FreePBX GUI just hangs and never completes.

PHP Fatal error:  Can't use function return value in write context in /var/www/html/admin/modules/sccp_manager/Sccp_manager.class.php on line 1903
Whoops\Exception\ErrorException: Can't use function return value in write context in file /var/www/html/admin/modules/sccp_manager/Sccp_manager.class.php on line 1903
Stack trace:
  1. () /var/www/html/admin/modules/sccp_manager/Sccp_manager.class.php:1903

**Comment by PhantomVl** [comment]
This function is not called during installation. If you get this error during use, it means that the installation is not done correctly.

**Comment by kh0952** [comment]
Is the module installation from the FreePBX GUI logged somewhere?  On occasion I can get it to go past "Loading" to "Installing sccp_manager" but the install hangs there.  9 times out of 10 it never gets past "Loading."  That is why I used FWConsole to attempt the install and saw the above error.  I have completely started over 3 times and keep getting the same result.  Installing this on FreePBX 13 with Asterisk 13 on CentOS6.

**Comment by PhantomVl** [comment]
I tried to write step by step instructions. https://github.com/PhantomVl/sccp_manager/wiki
Perhaps you have something not done.
