### ISSUE TITLE
TimeZone Codes. - 

### ISSUE THREAD

**Issue by TheBaldOne** [PhantomVl/sccp_manager#16]
Hi.

Sorry i had not got back to you but have been away. The New Zealand code is still incorrect.
Please have a look at the follow website for all the correct Cisco Local Time Zone names.
[http://usecallmanager.nz/sepmac-cnf-xml.html#networkLocale/timeZone](http://usecallmanager.nz/sepmac-cnf-xml.html#networkLocale/timeZone)
In your code you just have New Zealand/Daylight Time it should be 
New Zealand Standard/Daylight Time

**Comment by PhantomVl** [comment]
I have corrected  Cisco Local Time Zone names (SEPxxx.conf.xml). I unfortunately do not know under what conditions it begins to work but this time setting. Currently I see that the phone sinhroniziruete time with the sccp  server, and then performs the offset according to the setting  on the tab SCCP Phone Manager.

**Comment by TheBaldOne** [comment]
The issue that i have found is, If i use the New Zealand/Daylight Time that is being created in the SEPxxx.conf.xml file with the Time Zone offset of  GMT +12 the phones time is out by 1 Hour ( Due to New Zealand Daylight Savings Time) if i manual set 'New Zealand Standard/Daylight Time' in the SEPxxx.conf.xml and set the Time Zone offset to GMT Time then the phones show the correct date and time.

**Comment by PhantomVl** [comment]
Yes indeed it works on your scheme ! Well the problem close ? Basic time zone is written correctly ?
