### ISSUE TITLE
DTMF

### ISSUE THREAD

**Issue by NightShift21** [PhantomVl/sccp_manager#18]
When you setup the phone device, can you add an option to set the DTMF mode since not all phones (especially older versions) do not support rfc2833 (inband) dtmf.
I believe the dtmf is normally set in the sccp_hardware.conf but when using SCCP Manager there's no sccp_hardware.conf file anymore.

`force_dtmfmode = auto        ; auto, skinny or rfc2833. Some phone models with bad firmware do send dtmf in a messed up order and need to be forced to skinny mode.`

**Comment by PhantomVl** [comment]
"Force_dtmf is only required in very strange situations where normal behaviour does not work (for example when combined with Nat and directrtp it is sometimes necessary to force inband dtmf)." 
If you really need this option then you need to edit the following files: instal.php, sccpgeneral.xml.v431
>instal.php -> Line number 156 -> //            'force_dtmfmode'  - remove coments
>sccpgeneral.xml.v431 -> Line number 1101 -> 
           <item type="IS-disabled" id="6" seq="99"> 
                  change to 
           <item type="IS" id="6" seq="99">

**Comment by PhantomVl** [comment]
"Force_dtmf  - set in the basic configuration.
