### ISSUE TITLE
Second Dialtone Digit Value 0 (zero)

### ISSUE THREAD

**Issue by SebDE** [PhantomVl/sccp_manager#28]
I have a problem any time I change the "Secondary dialtone digits" to 0. If i look in the SQL DB i can see that there is a NULL value saved, but not a (int) 0. I looked at the sources and try to find the place where i can change the condition for this check (possible use of empty and not of isset) but I had no success. Can you give me a hint where i can find the place. Thanks !

**Comment by PhantomVl** [comment]
Fix

**Comment by SebDE** [comment]
many thanks - works like a charme !
