### ISSUE TITLE
SCCP MANAGER PROBLEMS

### ISSUE THREAD

**Issue by ribped** [PhantomVl/sccp_manager#30]
Hello, i have installed this manager to help me with my sccp phones.
I have followed the step by step, and everything have gone well, but i was testing with an ip comunicator, at first everything had gone well, but after a restart to the device from the page, the IP comunicator had gone wrong and cannot register again stays on ip configuration..
![2](https://user-images.githubusercontent.com/46194878/50482405-3d755480-09de-11e9-96e3-63f8283a4d49.png)
But at first it was working
![2](https://user-images.githubusercontent.com/46194878/50482443-7ad9e200-09de-11e9-862a-462f80abbe57.png)

**Comment by PhantomVl** [comment]
You need to see the logs of the phone. Perhaps the problem in the dhcp / tftp / http settings. The device can not correctly get the IP address and IP Options.

**Comment by ribped** [comment]
Hello again, i haver seen all that and its fine...today i changed the
machine to its location, it will be offline during work. But today i had
changes, i had connected an 7911 and it has done and upgrade trhought TFTP.
But the problem continues, it does not register, in fact it doesnt appear
on MySQL. But strangely when i have putted the hotline up the sccp phones
started to appear on manager, but it gets stuck on hotline. Otherwise they
dont appear..
Please see the screenshots...
Sorry for muito English.
Thanks you

Na(o) sexta, 28/12/2018, 07:14, Phantom <notifications@github.com> escreveu:

**Comment by PhantomVl** [comment]
Actually, I do not understand what you are doing. 
Preparation of the system takes place in several stages ( https://github.com/PhantomVl/sccp_manager/wiki/step-by-step-instlation ): 
1) Asterisk installations 
2) Installation chan_sccp
3) Installing and configuring service dhcp (options 150, 66... ) 
4) Installing and configuring service tftp ( /tftpboot + firmware + permission) 
If you have done everything correctly at this stage, we proceed to the next stage. (You can make sure that it works correctly in the settings menu of the phone)

Now as for the modes of operation - hotline. This mode is convenient to enable when configuring the server and devices. In this mode, all devices can connect to the server and you can assign the extensions to devices.
You will need to check the /tftpboot directory, there should be device files. (Files are recreated by pressing the "Cteate CNF" button.)

**Comment by ribped** [comment]
Thanks you for answering.
Ok, i have installed everything by following the step by step. The first
time i have tested, the sccp manager, my IP comunicator, was working fine,
but as i had said early, after a reset the IP comunicator could not
register again, you have Said on dieta e-mail ir could be a problem with
conectivity, but i tried a cisco 7911, and the sccp manager did not find
the phone even if i manualy insert it.
The lines and the manual added phone appears on mySQL, and so i tried to
delete the IP comunicator and the 7911, from the phone manager on sccp
manager, and had connected them again...
There is no problem on connectivity since the 7911 did a upgrade on boot.
The asterisk cli, keep saying device unknow, and the 7911 keeps saying
device could not register...
So i began to tamper with server config on the sccp manager, i had tried to
bind the address, but it didnt work...
I have done a reset to the original config, on the server config, on the
sccp manager, but this time i had enabled the hotline, and voila the phones
started to appear on the phone manager on the sccp manager, but i cannot
Change it line it keeps going to the hotline...
I wonder why is this happening... This, if i am not mistaken, is the last
screenshot that i sent...
I hope this time you have understand it...
Could you Help...
Thanks you on advance....

Na(o) sábado, 5/01/2019, 20:45, Phantom <notifications@github.com> escreveu:

**Comment by ribped** [comment]
Hello. Tomorrow i Will make new prints with newly created extensions, and
try create new cnf files, and reportagem back to you.
Thanks.

Na(o) domingo, 6/01/2019, 14:26, Phantom <notifications@github.com>
escreveu:

**Comment by ribped** [comment]
Hello.
Like I have said, today i have made what you said, so lets begin.
First i made screenshots wiht defaults configuration... (Server config.png,
server config 2.png, tftpboot_default.png);
I had disabled the hotline on server config (sccp manager) and created new
lines (sccp manager)( lines_created.png, Lines_in_mysql.png), after that i
connected a 7911 phone and the result is - 7911_without_hotline.png; The
phone display "device unknow";
After that i had enabled the hotline (hotline config.png), and now i can
see the phones on sccp manger(PHONES-HOTLINE.png), on mysql
(PHONES-SQL.png) and on asterisk CLI (7911_1.png, 7911_2.png).
And the tried to do your steps (assign a line and create cnf files) and the
result
is CNF-CREATED.png, CNF-TFTPBOOT.png, CIPC-CONFIG_1.png,
CIPC-CONFIG_2.png, CIPC_WIth
LINE.png; as you can see the phone as a line atributed but keeps on
hotline, the same happens with 7911 phones.
A did a reset to 7911 from sccp manger and the output is reset from sccp
manager.png, reset from sccp manager (7911)_1.png, reset from sccp manager
(7911)_2.png, reset from sccp manager (7911)_3.png, reset from sccp manager
(7911)_4.png, reset from sccp manager (7911)_5.png, reset from sccp manager
(7911)_6.png, reset from sccp manager (7911)_7.png, reset from sccp manager
(7911)_8.png, reset from sccp manager (7911)_9.png, reset from sccp manager
(7911)_10.png...
I hope with this you can help me resolve my problem, since the phones
cannot register like its suposed to be...
As an help i supply the sccp.conf that i had and an example cnf from a 7911.
Thank you....



Pedro Ribeiro <p.ribas1985@gmail.com> escreveu no dia domingo, 6/01/2019
à(s) 17:55:

**Comment by PhantomVl** [comment]
I do not see the images attached by you.
https://gitter.im/sccp_manager/community

**Comment by ribped** [comment]
https://files.gitter.im/sccp_manager/community/cA3U/SCCP-MANAGER.docx

I hope With this file you can help me...........

**Comment by ribped** [comment]
Things are working now, it was necessary to add some lines to "extconfig.conf":

[settings]
sccpdevice=mysql,sccp,sccpdeviceconfig
sccpline= mysql,sccp,sccpline

Thank you very much for the  help @PhantomVl
