### ISSUE TITLE
Проблема с кириллицей

### ISSUE THREAD

**Issue by vaDrn** [PhantomVl/sccp_manager#33]
Здравствуйте!
Возникла проблема с русскими символами на Cisco.
Когда на кнопки speeddial вписываю текст кириллицей, то в консоли Asterisk получаю ошибку:

`WARNING[5584]: sccp_utils.c:1862 sccp_utils_convUtf8toLatin1: SCCP: Iconv: illegal character.`

Проверял на телефонах Cisco 7912, 7960+7914

В качестве базы данных стоит MariaDB. Web-интерфейс SCCP Менеджера корректно сохраняет текст в базу данных и корректно отображает, если снова зайти в редактирование устройства.

Можете подсказать в чем может быть проблема?

Версия FreePBX 14.0.5.2
SCCP Manager версия: 13.0.0.2 Stable

**Comment by PhantomVl** [comment]
Добрый день ! 
Необходимо проверить, что БД, таблицы и столбцы таблиц находятся в одной кодировке. 
Желательно использовать COLLATE='utf8_bin', 
Добавить в файл res_mysql.conf стоку dbcharset = utf8
Иметь русскую локаль для телефонов

И еще не проверенно но отредоктировать файл sccp_utils.c  > line: 1834:
__sccp_iconv = iconv_open("ISO8859-1", "UTF-8");
на 
__sccp_iconv = iconv_open("CP1251", "UTF-8");
пересобрать chan-sccp

**Comment by vaDrn** [comment]
Спасибо, буду пробовать

**Comment by vaDrn** [comment]
Спасибо большое! Правка sccp_utils.c помогла - все работает :ok_hand:

**Comment by PhantomVl** [comment]
Через 1-2 недели будет выложено исправление включающее решение по данной проблеме. 
Ветка https://github.com/chan-sccp/chan-sccp уже содержит данный фикс. 
Но лучше будет обновит все сразу.
