### ISSUE TITLE
config_options.c: Unable to set default for

### ISSUE THREAD

**Issue by bknv** [PhantomVl/sccp_manager#40]
Hello. When i enter in setting SCCP CONNECTIVITY , i get problem with Chan_PJSip Endpoints. They are no longer available and asterisk display message : 
ERROR[23565]: config_options.c:946 aco_set_defaults: Unable to set default for 4710;@c6154c7adafa6e303543e8b6335f1698, qualify_timeout=3.0

rebooting core solves the problem, but until I enter in setting SCCP CONNECTIVITY.

PBX Firmware:12.7.6-1904-1.sng7

**Comment by PhantomVl** [comment]
HTTP Manager does not interact with the asterisk core. What version of asterisk and freepbx do you have installed ?
Can you send me screenshot pages "Sccp info" on the chat ? https://gitter.im/sccp_manager/community

**Comment by bknv** [comment]
Completed in commit 
https://github.com/chan-sccp/chan-sccp/commit/a27a98cc7785ea3e0d5d8cfe23fc9952776b3411
