### ISSUE TITLE
Error when trying to edit device

### ISSUE THREAD

**Issue by vaDrn** [PhantomVl/sccp_manager#45]
When I add new sccp phone device everything is working ok. But if I try to edit it afterwards I got an error "Invalid argument supplied for foreach()"

![image](https://user-images.githubusercontent.com/48777021/62500184-7d849b80-b839-11e9-9c9c-fbdc516de490.png)

I've use master branch of sccp manager for installation
freepbx version 14.0.10.3
asterisk version 13.22.0
xml version 13.0.2
sccp_class version 11.3.v432
core_sccp version 4.3.2

maybe I missed something during install?

**Comment by josh2893** [comment]
Have you tried any other branch? Master hasn't been touched for ages. I'm running dev with 0 issues.

**Comment by PhantomVl** [comment]
Hi ! 
You need to switch to the extension_mobility repository
>      git checkout extension_mobility

**Comment by PhantomVl** [comment]
Now I work in a branch extension_mobility. Repositories "master" and "develop" - saved for compatibility with old versions of chan_sccp

**Comment by vaDrn** [comment]
switching to extension_mobility branch fixed the issue.
Big thanks for the help ( o 3o)/
