### ISSUE TITLE
tftpboot language folder issue

### ISSUE THREAD

**Issue by vaDrn** [PhantomVl/sccp_manager#46]
This is strange one: sccp manager gets localization files only from _/tftpboot/language_ folder but phone itself tries to get language files from _/tftpboot_ folder.

**Comment by PhantomVl** [comment]
https://github.com/PhantomVl/sccp_manager/wiki/Instal-on-CentOS-7
> Download and install Provision Sccp.

**Comment by vaDrn** [comment]
Thank you for the help! Everything seems to be working ok.

**Comment by vaDrn** [comment]
just noticed that 7940-60 firmware request string isn't full

RRQ from 192.168.189.125 filename P0030801SR02.loads remapped to firmware/7940/P0030801SR
Client 192.168.189.125 File not found firmware/7940/P0030801SR

Is there articles on this string manipulation syntax?
