### ISSUE TITLE
Dial String is Missing

### ISSUE THREAD

**Issue by ksivramkrish** [PhantomVl/sccp_manager#47]
We successfully installed and configured the SCCP manager. While configuring the extensions Dial is missing SCCP/XXXX. If we want to add multiple dial string for simultaneous calls how we can add it? For example SCCP/XXXX&SIP/XXXX or SCCP/XXXX&SCCP/XXXX.

**Comment by PhantomVl** [comment]
Very little information to understand your problem.

**Comment by ksivramkrish** [comment]
For simultaneous ring for 3 extensions, we are adding the dial string like that SCCP/XXX1&SIP/XXX2&SCCP/XXX3. If we dial XXX1 it will ring on all the 3 extensions XXX1, XXX2, and XXX3. In our sccp extension dial string is missing.
![dial_string-xxxx](https://user-images.githubusercontent.com/38924638/64279224-2810dc80-cf14-11e9-9e46-e7319d83b7f9.PNG)

**Comment by PhantomVl** [comment]
The dial string associates the phone number with the sccp device. If you need to create a number coming to several devices, you must use other method of asterisks (virtual number, call group, etc.).

**Comment by dkgroot** [comment]
When writing your own dialplan you can just do:
```
Dial(SCCP/${EXTEN:0:3}1&SIP/${EXTEN:0:3}1, 60);
```
So there should be nothing holding you back.
So making an extension should be the way to go. However you seem to want to replace "XXX" in the dialstring. I think that's not [easily done/possible] directly in the web frontend. I think you would need a extensions-custom.conf entry, and call that. Please do note, i don't know a lot about freepbx.

**Comment by dkgroot** [comment]
This is dialplan (asterisk/freepbx) stuff, but not related to chan-sccp or sccp_manager in any way. Have a look at [this wiki page](https://wiki.freepbx.org/display/FPG/Ring+Groups+Module) about ringgroups.

**Comment by ksivramkrish** [comment]
Hello dkgroot and PhantomVl,

Thanks for your valuable input. I appreciate your help.

**Comment by dkgroot** [comment]
@ksivramkrish If this has resolved the issue you raised, then please close this issue report. If not, please re-explain the problem you might be having.

**Comment by dkgroot** [comment]
Did you solve the issue ?
