### ISSUE TITLE
sccp cnf.xml call manager ip address node

### ISSUE THREAD

**Issue by vaDrn** [PhantomVl/sccp_manager#48]
I have server that uses two interfaces with different subnets on each one. But my ip phones should connect only through one of these interfaces. How I can select which interface will be put into generated cnf.xml file?

**Comment by josh2893** [comment]
Do you mean this?
![image](https://user-images.githubusercontent.com/43034295/64916304-0e8e5100-d7ae-11e9-9416-ab8d557d221d.png)
![image](https://user-images.githubusercontent.com/43034295/64916306-11894180-d7ae-11e9-9cc2-1b041bdd61f6.png)

**Comment by PhantomVl** [comment]
Sip clients can connect to any IP address on which the SIP server is running. I get this information from asterisk. Your image is SCCP server settings, but not sccp or sip client.

**Comment by vaDrn** [comment]
will try this out, thx.
