### ISSUE TITLE
7960 with two 7914 expansion modules cnf file generation issue

### ISSUE THREAD

**Issue by vaDrn** [PhantomVl/sccp_manager#49]
When sccp manager creates cnf file for 7960 phone, it appends at the end of the config file information about expansion modules. For some reason it only add info about one expansion module:

![image](https://user-images.githubusercontent.com/48777021/66728982-40253580-ee9c-11e9-9f84-c7196518dcb8.png)
![IMAG1136](https://user-images.githubusercontent.com/48777021/66728990-4c10f780-ee9c-11e9-96c4-e1ae63036e09.jpg)

If I add required info by hand everything works ok

**Comment by Cynjut** [comment]
The code I wrote for FreePBX 1.8 was never tested with two sidecars.

**Comment by PhantomVl** [comment]
* Update git project

**Comment by vaDrn** [comment]
Sorry for bothering.
Phone server already in use, so I'm kinda afraid to break it. So just to be sure: I just need to go into `/var/www/html/admin/modules/sccp_manager/` and call `git pull` and then restart server with `fwconsole restart`?

**Comment by PhantomVl** [comment]
Backup  dir /var/www/html/admin/modules/sccp_manager/

    cd /var/www/html/admin/modules/sccp_manager/
    git fetch
    git pull

no other action is required
