### ISSUE TITLE
Hint string length in button config HTML is truncated + Suggestion

### ISSUE THREAD

**Issue by KCross84** [PhantomVl/sccp_manager#53]
In the button configuration screen, the dropdown containing all extensions truncate text for length. This causes some hints not to work and it may not be apparent why until the user inspects the resulting generated HTML. Please see attached image.

Additionally, the user could gain more functionality by combining the dropdown with a text entry field by using the datalist element for custom hint locations. Example:

```
<input type="text" name="hntCstm" list="lstExtns">
<datalist id="lstExtns">
  <option value="4101@from-internal">4101/Kirk Cross</option>
  <option value="4102@from-internal">4102/L. Jensen</option>
  <option value="4103@from-internal">4103/Warehouse I</option>
  <option value="5199@mesg-functs">5199/Group Message</option>
  <option value="HA14073315882@from-really-long-list">Toggle Garden Lights</option>
        _Etc..._
</datalist>
```

Thank you for your assistance.
Kirk

![image](https://user-images.githubusercontent.com/47312078/69903914-6f690680-1365-11ea-937b-d180da9301d2.png)

**Comment by PhantomVl** [comment]
Yes, I am aware of this problem, I use the standard methods of obtaining information through the CLi. If you send the command 
*CLI> core show hints 
you will also get a cropped string.
An alternative way of obtaining data is not yet ready at the moment.

**Comment by KCross84** [comment]
Ah, I didn't realize that the string was cropped in output there. I saw a video a long time ago where someone in the CLI appended something and got "wide output" that made the columns wide enough to display the entire hint. At any rate, I tried editing the form to produce the suggested data list and it worked, however, the results were not persistent. Perhaps if there were a text box AND the drop-down, and the form were to save them appended so that even if you added the last few letters OR selected nothing from the list and just typed in a hint manually, it would still work.

**Comment by KCross84** [comment]
Or, better yet, when you select a hint from the drop-down, it would put the text from the selection into the text box. That way, you could fill it out by selecting a hint OR just typing in one manually. That seems like the simplest way to go.

**Comment by PhantomVl** [comment]
This is the wrong way. There is a special AMI interface that is devoid of these problems.

**Comment by KCross84** [comment]
I'm talking about adding buttons to the phone, not adding entries programmatically. I'm trying to suggest things that you might do to overcome the cropped hint limitation in the next release. As of right now, the only way in manager to get speed dials is to select from the list and if the hint is cropped, I've found no other way to add the button except for editing the live form.

Just attempting to help.

**Comment by PhantomVl** [comment]
![изображение](https://user-images.githubusercontent.com/7577494/69950643-bfca9a80-1504-11ea-92ad-0a8f5ceebfa2.png)

**Comment by KCross84** [comment]
That field says "phone"—which I thought was the place to enter the number to be dialed, but you're saying that I can enter a hint manually here? What's the hints button for then? When someone looks at this, their first thought is that they're getting a speed dial, that will dial the number in the first field and light according to the hint in the second.

Edit: I just tried this and it gives a regular speed dial button with no hinting. When I go back to the page, the hint box is selected.

**Comment by PhantomVl** [comment]
plz. Open chat https://gitter.im/

**Comment by PhantomVl** [comment]
Plz. Open chat https://gitter.im/

**Comment by KCross84** [comment]
Workaround, per PhantomVI: Enter nbrToDial, nbrToDial@Context in first field. Do not click Hint button. Must re-enter this if you make additional changes as this is a workaround and Manager will revert to previous values.
