### ISSUE TITLE
Module installation failed no sccp device table

### ISSUE THREAD

**Issue by Od1waN** [PhantomVl/sccp_manager#55]
Hi,

i will install the module to a raspPBX and chan_sccp is installed. I using the latest Version from freepbx. But the installation failed with !!!! Installation error: Can not find required sccpdevice table !!!!!! ::

`/var/www/html/admin/libraries/utility.functions.php
 
function compress_framework_css() {
    compress::web_files();
}
 
/**
 * Throw FreePBX DIE Message
 * @param string $text The message
 * @param string $extended_text The Extended Message (Optional)
 * @param string $type The message type (Optional)
 */
function die_freepbx($text, $extended_text="", $type="FATAL") {
    if(is_object($extended_text) && method_exists($extended_text,"getMessage")) {
        $e = $extended_text;
        $extended_text = htmlentities($e->getMessage());
        $code = $e->getCode();
        throw new \Exception($text . "::" . $extended_text,$code,$e);
    } else {
        $extended_text = htmlentities($extended_text);
        throw new \Exception($text . "::" . $extended_text);
    }
}
 
/**
 * Get the FreePBX/Framework Version
 * @param bool $cached Whether to pull from the DB or not
 * @return string The FreePBX version number`

I don't know what to do or i missing some functions or modules?!

so long
Nico

**Comment by PhantomVl** [comment]
You may not have created a basic set of tables before installing the module.
Check your steps with the Centos instance example
https://github.com/PhantomVl/sccp_manager/wiki/Instal-on-CentOS-7

**Comment by Od1waN** [comment]
Hi,

cool this works now. Thanks for you fast help.
