### ISSUE TITLE
Error Class 'ZipArchive' not found

### ISSUE THREAD

**Issue by Od1waN** [PhantomVl/sccp_manager#56]
Hi,

i have a freshinstall from rasPBX and sccp. when i install sccp manager i become this as error. zip and gzip is installed on my pi. 

`    
    $zip = new \ZipArchive();
    $filename = $dir . "/sccp_instal_backup" . date("Ymd"). ".zip";
    if ($zip->open($filename, \ZIPARCHIVE::CREATE)) {
        foreach ($backup_files as $file) {
            foreach ($backup_ext as $b_ext) {
                if (file_exists($dir . '/'.$file . $b_ext)) {
                    $zip->addFile($dir . '/'.$file . $b_ext);`

so long

**Comment by PhantomVl** [comment]
Hi. This problem is due to the lack of support for zip in php. You can try   ...

---
sudo apt-get install php-zip
sudo phpenmod zip
sudo service apache2 restart
---
Check 

 php -m 
 ....
 zip
 zlib

**Comment by Od1waN** [comment]
Hi, i installed php-zip and phpenmod zip gave back 
`WARNING: Module zip ini file doesn't exist under /etc/php/7.0/mods-available
WARNING: Module zip ini file doesn't exist under /etc/php/7.0/mods-available
`
and php -m
`[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gettext
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
`
zip is installed with zip 3.0.

**Comment by PhantomVl** [comment]
Hi ! 
This problem is the lack of a standard PHP library
https://www.php.net/manual/en/book.zip.php

pecl install zip
(you need reboot or restart httpd service ) > check (test)
php -r 'echo ZipArchive::CREATE;'

Othe 

apt-get install php7.0-zip
or 
yum install php70-php-pecl-zip

echo "extension=zip.so" >> /etc/php.d/zip.ini

**Comment by Od1waN** [comment]
Hi, apt-get install php7.0-zip was the solution and a reboot from apache2. Now the manager is working, thx again.
