### ISSUE TITLE
Adding a Phone

### ISSUE THREAD

**Issue by SimplySynced** [PhantomVl/sccp_manager#7]
Hello,

When addin a phone through the SCCP Phone Manager.  Right now when I do my SEP ID under the general device configuration it will add but does not connect, even if it is the SEP currently mines SEP001193123610, Also Type I have a 7970 but it does not have this listed in drop down.  If I go to save right now it says 

Undefined index: Russian_Russia
File:/var/www/html/admin/modules/sccp_manager/Sccp_manager.class.php:2167

It saves but does not connect.  The interesting thing is if I put SEP001193123610 in the field it adds without any error shows the ID of SEPSEP001193123 in the device SEP ID field but still does not connect.   I did have 2 occasions where the phone did show up and connected but when I deleted the line I created it would remove both.  Not sure what is going on but please let me know how I can help.

**Comment by SimplySynced** [comment]
possibly unrelated but I can't get a remote phone to connect.

**Comment by PhantomVl** [comment]
Problem with "Undefined index: Russian_Russia" is Fixed.
The list in drop down of devices, displays only those that have the status "Enabled" on the page "SCCP Advance Server Configuration"
