### ISSUE TITLE
SCCP Extension Details not populating

### ISSUE THREAD

**Issue by KCross84** [PhantomVl/sccp_manager#70]
When filling out the SCCP tab in the extension detail screen, the field data saves and is active on the phone, however, when going back into the extension detail, none of the saved data shows up.
![image](https://user-images.githubusercontent.com/47312078/79750138-0cf1b200-82d6-11ea-87bf-f00bc45fac64.png)

**Comment by PhantomVl** [comment]
Fix

**Comment by KCross84** [comment]
Problem present in certain versions. Fixed in latest release.

To remedy, issue the following MySQL commands:

> ALTER TABLE sccpline ADD COLUMN videomode ENUM('user','auto','off') NULL DEFAULT NULL;
