### ISSUE TITLE
Error on delete device

### ISSUE THREAD

**Issue by SeSti4** [PhantomVl/sccp_manager#71]
Hello,
system is:

FreePBX 15.0.16.49
Asterisk 16.9.0
Sccp ver.4.3.2 r433 Revision :10887 Hash :7cfe28a
latest Sccp Manager (on 21.04.2020).

When i delete device (phone), i have a error:

Unable to locate the FreePBX BMO Class 'Strpos_array'A required module might be disabled or uninstalled. Recommended steps (run from the CLI): 1) fwconsole ma install strpos_array 2) fwconsole ma enable strpos_array
File:/var/www/html/admin/libraries/BMO/Self_Helper.class.php:212

![error](https://user-images.githubusercontent.com/51790542/79867092-752fb900-83e6-11ea-9279-4ceec98daf73.jpg)

**Comment by PhantomVl** [comment]
Hello ! 
plz. update from git

**Comment by justinkoby** [comment]
@PhantomVl I was having that issue as well. Just have been dealing with other issues before I turned to that one.

The new update that I got today from git resolved the BMO Class error when deleting a device that I was getting. Just wanted to let you know it did help at least one person.

**Comment by SeSti4** [comment]
@PhantomVl Thanks! It's work!

**Comment by PhantomVl** [comment]
Thank you for letting me know that the problem has been fixed !
