### ISSUE TITLE
SIP Device? checkbox missing on "add model menu"

### ISSUE THREAD

**Issue by alexanderkitanov** [PhantomVl/sccp_manager#77]
I'm trying to create a profile for a Cisco 9951 sip phone but the checkbox "SIP Device" is missing on "add model menu" I will be grateful if you have any suggestions?

![image](https://user-images.githubusercontent.com/47685749/83608158-1339a600-a585-11ea-8b5e-397b30f73a82.png)

**Comment by PhantomVl** [comment]
Hi ! You need to fill in all the fields for your phone. Model 9951-sip

**Comment by alexanderkitanov** [comment]
Hello, I'm filling all fields in the form, but i got no "SIP Device?" checkbox in the Modal Title form (as shown in issue#43.  Please avise! 

![sip](https://user-images.githubusercontent.com/47685749/84250545-d9cce180-ab14-11ea-98f3-1b654b243232.png)

**Comment by josh2893** [comment]
Please put the below data into the following fields  
Device Model:  9951-SIP
vendor name: CISCO-SIP
Load Image: sip9951.9-2-2SR1-9
Model Information ID:  loadinformation537
Model Template XML: SEP0000000000.cnf.xml_99xx_sip_template

Ive uploaded firmware and template files to my google drive you can use. 
(https://drive.google.com/drive/folders/1CCqc1Sm2iGNRKM5DXfIyzsyCmzpL-c1d?usp=sharing)

**Comment by alexanderkitanov** [comment]
Thank you for the hint **Josh2893** !
I created the new phone according to your advise and with your template and firmware, but still i have no Sip Device? checkbox in the Modal Title form.
also i'm not able to select the so-created phone from Device SIP Phone / Add Device Phone menu.
Please advise!
