### ISSUE TITLE
DB error

### ISSUE THREAD

**Issue by beom80** [PhantomVl/sccp_manager#78]
Hi,

I have installed this on a Raspberry Pi4B 4GB using Raspbx however when I try to use it, I keep getting the same or similar errors. I also installed chan_sccp from APT.

"Cannot use object of type DB_Error as Array File:/var/www/html/admin/sccp_manager/Sccp_manager.class.php:977"

I am guessing that it is related to the realtime database. I am using MySQL/MariaDB and have imported the mysql-v5_enum.sql in.

I have tried setting a new password for the user 'asterisk' and adding the 'asterisk' user to the asterisk database and changing the password in the config files.

Regards,
Ben.

**Comment by PhantomVl** [comment]
Hi ! You can imported the mysql-v5_enum.sql before Install Sccp Manager.

**Comment by beom80** [comment]
Hi,

I did import the mysql-v5_enum before installing Sccp Manager.

I also tried removing and reinstalling Sccp Manager as well as a fresh system install and going through all the steps in order again.

**Comment by PhantomVl** [comment]
Ок. Go to the chat https://gitter.im/sccp_manager/community. 
I am available to chat on business days from 14-17 UTC.

**Comment by beom80** [comment]
Hi,

I found that root cause of the problem, I forgot that when I tried installing the module, it gave me an error in the install.php. I commented out a portion to try and get around it but I obviously commented out something that was needed. I changed what I commented out and the script installed and doesn't give the error anymore.

I have attached an image showing the script error.

![Screen Shot 2020-08-22 at 6 35 18 pm](https://user-images.githubusercontent.com/69620019/91125083-3a1afa80-e6e4-11ea-8850-e735f5e2af8f.png)

The only problem I am having now is that I get 'registration rejected' on the phones and am not sure if it is related to the commented out section.
![Screen Shot 2020-08-25 at 3 14 29 pm](https://user-images.githubusercontent.com/69620019/91125745-c679ed00-e6e5-11ea-8148-177d2ed283a5.png)

**Comment by PhantomVl** [comment]
Hi ! 
The ZipArchive class is used by other asterisk modules as well. You need to add it to the system. One of the following commands will help you do this: 
sudo apt-get install php-zip
sudo phpenmod zip
sudo apt-get install php7.0-zip

and  restart Apach :
sudo service apache2 restart

**Comment by beom80** [comment]
Hi,

Thank you for all your help. That was indeed the problem.
