### ISSUE TITLE
Services URL

### ISSUE THREAD

**Issue by jttri777** [PhantomVl/sccp_manager#88]
Hello,

Thanks for a great piece of software!

I have set the services URL in the sccp_manager GUI, and I can see that this is output to the xmldefault.cnf.xml file. This file seems to be ignored, however, by my 7975. If I manually set the URL in the sepmac.xml config file myself, everything works, however this is overwritten when the config is changed in the sccp_manager GUI.

I remember reading somewhere that on 7975 SCCP firmware version 9 the xmldefault.cnf.xml file is ignored in favor of an individual sepmac.xml file.

Thanks,
James.

**Comment by jttri777** [comment]
Found it here:

https://community.cisco.com/t5/ip-telephony-and-phones/cp-7961g-not-taking-sepmac-config-after-sip-firmware/m-p/3413952

"it won't work because if the phone is running 9.X firmware it will IGNORE the XMLdefault.cnf.xml file.
All changes need to be done on the SEPmacaddress.cnf.xml file."

If that's of any help?

Thanks,
James

**Comment by PhantomVl** [comment]
Hi ! 
File "XMLdefault.cnf.xml" used only by devices that do not have the "SEPmacaddress.cnf.xml " file.
Settings such as "services URL" are generated for each phone. They must be present in all configuration files. 
Maybe you just need to click "CreateCNF"
Or it's some new error in the code.

**Comment by jttri777** [comment]
Hi, thanks for your help.

When I click CreateCNF it does generate new configuration files for the selected phones. The following line is added:

![image](https://user-images.githubusercontent.com/12187650/99189969-e6a4cf80-275b-11eb-8a57-fceace3e6afa.png)


which is obviously commented out, and does not follow what I have in the services URL path under the SCCP Device URL tab on the  SCCP Server Settings page.

Thanks for your help
James.

**Comment by jttri777** [comment]
![image](https://user-images.githubusercontent.com/12187650/99195311-dc46fd80-277c-11eb-9161-369aacad7cf9.png)

This seems to be a problem with the provided 797x template. The line seems to be commented out (as shown in the picture above).

Upon removing the comment sections from the services line, the URL is automatically added to the config file as expected.

Thanks for your help,
James.

**Comment by jttri777** [comment]
https://github.com/PhantomVl/sccp_manager/blob/extension_mobility/conf/SEP0000000000.cnf.xml_797x_template


This template seems to have been recently edited to accommodate some features for future development (https://github.com/PhantomVl/sccp_manager/commit/2d57895fc156c8de75f34064c2cd3413e389db4a) however, the services URL has been left commented out, which has prevented the URL from being added during the config generation.

Thanks,
James
